<?php

namespace App\Faker;
use Faker\Provider\Base;

class ApartmentNameProvider extends Base
{
    protected static $apartmentNames = [
        'The Luxury Collection Hotels & Resorts',
        'Marriott',
        'Regency Hotel',
        'Hilton Walt Disney World',
        'Disney’s Wilderness Lodge',
        'Disney’s Yacht Club Resort',
        'Mandarin Oriental',
        'Four Seasons Hotel',
        'Residence Inn by Marriott',
        'El Rancho Casino',
        'Clarion Hotel and Casino',
        'Continental Hotel and Casino',
        'Cosmopolitan of Las Vegas',
        'Waldorf Astoria Hotels & Resorts',
        'Ritz Plaza Hotel',
        'W Hotel',
        'Yosemite Lodge at the Falls',
        'St Regis Hotels',
        'Hyatt',
        'DuPont Plaza Hotel',
        'Antlers Hilton Hotel',
        'The Stanley Hotel',
        'Hotel Bond',
        'Hollywood Plaza Hotel',
        'Fort Harrison Hotel',
        'Ahwahnee Hotel',
        'Belmond',
        'Rosewood Hotels & Resorts',
        'Aman Resorts',
        'The Peninsula Chicago',
        'Ritz-Carlton Hotel',
        'National Exchange Hotel',
        'Farmer’s Daughter Hotel',
        'Ace Hotel',
        'Great Gravity Hotel',
        'Your Tokyo Hotel',
        '5 Star Getaway',
        'Hotel Cirrus Shake',
        'Ube Hotel',
        'Going to Haven',
        'SleepyCrew Hub',
        'Gotham Hotel',
        'Giggle Resort',
        'The Enchanted Garden',
        'Hotel Lemonade',
        'Hotel Joy Stick',
        'Breeze Blows Hotel',
        'Wordly Traveller Hotel',
        'Cable Car Hotel',
        'Hotel Vitality',
        'Land’s End Resort',
        'Walkabout Beach Hotel',
        'Familiar Inn',
        'Sun and Sand Hotel',
        'The Better Inn',
        'Hotel Fusion',
        'The Enchanted Garden',
        'The Welcome Mat',
        'Priority Hospitality',
        'Country Charm Hotel',
        'Always Welcome',
        'The Glory Hotel',
        'Sandy Bloom',
        'Dream Desert Hotel',
        'Quirk Hotel',
        'Blue Moon Hotel',
        'Whale Cave Inn',
        'Hotel Jolly',
        'Bedrock N Roll',
        'Suprema Lodge',
        'SpinSurf Hotel',
        'Fairview Hotel',
        'Bourbon Bliss',
        'Hotel Happy Springs',
        'Green Lushy Hotels',
        'Soft Petal Hotel',
        'Quick Stop Hotel',
        'Palace Hotel',
        'Sunset Plains Hotel',
        'Secluded Hill Hotel',
        'Moss View Hotel',
        'The Gritty Palace',
        'Red Velvet Inn',
        'Sizzling Inn',
        'Hotel The Pie',
        'Mofo Cuzzi Inn',
        'Clean Convenience',
        'Newhouse Hotel',
        'Elephant Butte Inn & Spa',
        'Hotel Kuntz',
        'Grand Gross Hotel',
        'ABAD Hotels',
        'French Lick Resort',
        'Scandic Hell',
        'Grand Oral Hotel',
        'New Hangover Hotel',
        'Step Back Inn',
        'Morning Wood Hotel',
        'Somass Motel',
        'Hotel WhatsApp',
        'Amorous Feelings Hotel',
        'Worst Western Hotel',
        'Sweet Teen Hotel',
        'Hotel Space Mountain',
        'Wang Thong Hotel',
        'The Nobody Inn',
        'Ufuk Hotel Pension',
        'Wellness Hotel Harms',
    ];

    public function apartmentName(): string
    {
        return static::randomElement(static::$apartmentNames);
    }
}